### ISSUE TITLE
Option to set gas limit

### ISSUE THREAD

**Issue by zachdoty** [jamespic/SpaceSuit#2]
Trying to use this on the namebazaar dapp and the TX isn't confirming due to a low gas price.

What is the easiest way to make this use a higher gas price?

**Comment by jamespic** [comment]
The simplest way I can think of to implement this would be to add either a "minimum gas price" option or a "force override gas price" option to the options screen. I'm on the fence about which would be better, but both should be easy enough.

**Comment by zachdoty** [comment]
Thank you very very much! That makes life easier :)

On a side note... are you interested in having this project sponsored? We're an Ethereum startup currently in stealth mode and we're interested in sponsoring you in this SpaceSuit endeavor. Maybe we could chat about it over Skype, email, or telegram and I could share more about our project and see if it would be a good fit?

**Comment by jamespic** [comment]
Thanks, no problem.

Since this a side project (totally unrelated to my day job), I'm not sure I'd be able to make the kind of commitment that a sponsor would likely want, but if you want to talk about your project, the email address on my profile is the best way to reach me.

**Comment by jamespic** [comment]
Actually, now I think about it, it would be good to have some backing for bug bounties, if that would be viable.
