### ISSUE TITLE
Web3 Injection after document.ready event

### ISSUE THREAD

**Issue by AusIV** [jamespic/SpaceSuit#3]
There's been a discussion happening on Reddit, but this seems like a better venue to document the issue I'm seeing.

I have a dApp where people can claim an ERC20 token. We start out by making sure people have a Web3 browser and Ether, then give them the opportunity to claim the token.

As it's a pretty simple dApp, the core logic of each page is done as in-line javascript using jQuery. Intermittently, we are seeing that `window.web3 === undefined` at the time that our `$(document).ready()` function fires.

This can be observed at: https://get.embiggen.me/mbgnweb3.html

In the chrome dev tools, I've put breakpoints on line 76 of mbgnweb3.html (which is where we check for web3), and on line 34 of SpaceSuit/inpage.js? [sm], and most of the time our check for web3 happens before SpaceSuit injects web3.

I have noticed that if I already have the page in my browser cache and get a 304 not modified from the server, web3 injection happens after the ready function fires. If I clear the cache and do a hard reload, web3 injection generally happens before the ready function fires. 

I've tried moving my javascript out of the web page into a separate file, and I still observe the issue, with the same behavior around whether or not the page was cached by the browser.

**Comment by AusIV** [comment]
I also want to note that I'm happy to dig in and help out here if you can point me in the right direction. I understand this is a volunteer project, and I'm happy to help out where I can (aside from finding bugs).

**Comment by AusIV** [comment]
I updated to clarify that it's not ready by document.ready, but I found it is ready by window.load. I've updated my site to fire after window.onload, rather than document.ready, so I'm up and running with SpaceSuit.

It did work under Metamask, Toshi, and Cipher though, so by your definition of being bug-for-bug compatible with Metamask, this seems like a bug. I'll leave this open, but wouldn't object if you fixed this with a documentation update instead of a code change.

**Comment by jamespic** [comment]
If you've just updated the site, that would explain why I suddenly lost the ability to reproduce it!

I know the injection works slightly differently from MetaMask. MetaMask injects code with `<script>/* MetaMask code */</script>`, whereas SpaceSuit injects code with `<script src="path/to/code.js"></script>`. It would make sense if SpaceSuit's approach would introduce a delay whilst code is fetched, and that jQuery would regard this as "ready", but not loaded.

Leave it open. I'll try to validate this theory, and look into fixes.

**Comment by jamespic** [comment]
This should now be fixed in 0.2.7.
