### ISSUE TITLE
Add Buffer to Gas Limit

### ISSUE THREAD

**Issue by AusIV** [jamespic/SpaceSuit#4]
The gas estimation seems to be spot on, but since there's a possibility that events that happen between gas estimation and transaction confirmation, there's no guarantee that the real gas usage will reflect the estimated gas.

Metamask addresses this by setting the gas limit for a transaction equal to 1.5 times the estimated gas, capped at the block gas limit.

I think it would be pretty easy to add a middleware that would set the gas limit to 1.5 the estimated gas, but I'm not sure how to determine the block gas limit within a middleware.

**Comment by jamespic** [comment]
This is actually something that's weirdly clunky to do with `web3-provider-engine` (which may partly explain why Metamask are in the process of rewriting provider engine - I think the replacement's called `json-rpc-engine`).

You can make a call within a middleware with `this.emitPayload`, but if you're calling the same method you're handling, you might accidentally recurse infinitely.

Or if you call `next` with a callback, that callback can modify the returned value. This would be the obvious way, except that it can only modify *mutable* return values.

I reckon the least ugly way to handle this will be to create a new internal-use method `eth_estimateGasRaw`, and create a middleware that handles `eth_estimateGas` by calling `eth_estimateGasRaw` (via `emitPayload`) and returning 1.5× the result, and handles `eth_estimateGasRaw` by changing the method to `eth_estimateGas` before calling `next`. Which is still ugly, I know. 

And I should probably look at the progress of `json-rpc-engine`, and see if it smoothes off these sorts of rough edges.

**Comment by jamespic** [comment]
Thinking about this more, is the goal to increase the amount that we return from `eth_estimateGas`, or to increase the amount we default to when `eth_sendTransaction` doesn't include a gas limit?

Thinking about it, the latter seems more like the right approach. Any dapp that's had the decency to call `eth_estimateGas` is probably going to do something sensible with the value, so we should probably give them an honest estimate, whereas dapps that call `eth_sendTransaction` without a gas limit will mostly want it all to just be handled for them.

But maybe I'm just saying that because the latter would be easier! It would just be a question of calling `this.emitPayload` to get a gas estimate whilst handling `eth_sendTransaction`.

**Comment by AusIV** [comment]
Metamask gives the "correct" value for estimateGas, but sendTransaction uses min(1.5*gasEstimate, blockGasLimit). 

If it were just a matter of doing 1.5*gasEstimate, that would be a simple middleware along the lines of the gasPrice limiting middleware, Unfortunately, if 1.5*gasEstimate exceeds blockGasLimit the transaction will be dropped pretty quickly.

**Comment by jamespic** [comment]
I won't get chance to work on this properly until Sunday at the earliest, but I've put together a quick sketch of a middleware to do this: https://github.com/jamespic/SpaceSuit/blob/gas-buffer/middleware/gas-padding.js, as a starting point for conversation. I've chosen only to pad out the gas if there's no gas limit provided (I figure dapps that have done this have probably validated that these limits are correct), and I'm on the fence about whether to put a buffer around the block gas limit (use `0.95 * gasLimit`, or similar). I should probably check how MetaMask handles this, for compatibility.

**Comment by jamespic** [comment]
I've just released 0.2.3 which should fix this. Let me know if you have any problems.

**Comment by jamespic** [comment]
Fixed in release 0.2.3
