### ISSUE TITLE
How can I see if Spacesuit is working?

### ISSUE THREAD

**Issue by samir-85** [jamespic/SpaceSuit#5]
How can I see if
1) Spacesuit has recognized my Nano?
2) Spacesuit is working if my dapp? window.web3 is undefined, which leads me to the assumption that Spacesuit is not properly injecting ...

**Comment by AusIV** [comment]
@samir-85 - I believe SpaceSuit only works on https - if you're testing on http I don't think it will inject.

Once injected, you should be able to run something like:

    web3.eth.getAccounts(console.log)

which should print out the first 10 addresses on your Ledger.

**Comment by samir-85** [comment]
Thanks, using https is an important hint otherwise you are list. I
recommend putting that information into the readme.

Regards Samir

**Comment by jamespic** [comment]
I've added something to the documentation (https://github.com/jamespic/SpaceSuit/commit/734e19499a14524d5508871c1585fed478bb0535), but it'd be good to get a steer from a user on whether it's well-placed.

I might also add some kind of "config check" feature, to help identify common pitfalls (Ledger not plugged in, app not open, browser support disabled, contract data disabled, etc).

**Comment by samir-85** [comment]
From my perpective it is now adequately covered in the documentation.
